project:
  type: website
  output-dir: docs

website:
  title: "Liban Timir"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Resume
        href: LibanTimir_Resume_2024.pdf
      - about.qmd
      
format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual

